#
# CMake platform file for PS2 IOP processor
#
# Copyright (C) 2009-2010 Mathias Lafeldt <misfire@debugon.org>
#

SET(PS2SDK "$ENV{PS2SDK}")
IF (NOT PS2SDK)
    MESSAGE(FATAL_ERROR "PS2SDK env var not set.")
ENDIF (NOT PS2SDK)

INCLUDE_DIRECTORIES("${PS2SDK}/iop/include")
INCLUDE_DIRECTORIES("${PS2SDK}/common/include")

LINK_DIRECTORIES("${PS2SDK}/iop/lib")

# TODO get version from iop-gcc
SET(IOP_CC_VERSION "3.2.2")

SET(IOP_CFLAGS_TARGET "-miop")
SET(IOP_ASFLAGS_TARGET "-march=r3000")
SET(IOP_LDFLAGS_TARGET "-miop")

SET(IOP_CFLAGS "${IOP_CFLAGS_TARGET} -O2 -G0" CACHE STRING "IOP C compiler flags" FORCE)
SET(IOP_LDFLAGS "${IOP_LDFLAGS_TARGET} -nostdlib" CACHE STRING "IOP linker flags" FORCE)
SET(IOP_ASFLAGS "${IOP_ASFLAGS_TARGET} -EL -G0" CACHE STRING "IOP assembler flags" FORCE)

SET(CMAKE_C_FLAGS_INIT ${IOP_CFLAGS})
SET(CMAKE_CXX_FLAGS_INIT ${IOP_CFLAGS})
SET(CMAKE_EXE_LINKER_FLAGS_INIT ${IOP_LDFLAGS})

SET_PROPERTY(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)

SET(CMAKE_SHARED_LIBRARY_C_FLAGS)
SET(CMAKE_SHARED_LIBRARY_CREATE_C_FLAGS)
SET(CMAKE_SHARED_LIBRARY_LINK_C_FLAGS)
SET(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG)
SET(CMAKE_SHARED_LIBRARY_RUNTIME_C_FLAG_SEP)

SET(CMAKE_LINK_LIBRARY_SUFFIX)
SET(CMAKE_STATIC_LIBRARY_PREFIX)
SET(CMAKE_STATIC_LIBRARY_SUFFIX ".irx")
SET(CMAKE_SHARED_LIBRARY_PREFIX)
SET(CMAKE_SHARED_LIBRARY_SUFFIX)
SET(CMAKE_EXECUTABLE_SUFFIX ".irx")
SET(CMAKE_DL_LIBS)

SET(CMAKE_C_OUTPUT_EXTENSION ".o")

SET(CMAKE_FIND_LIBRARY_PREFIXES)
SET(CMAKE_FIND_LIBRARY_SUFFIXES ".irx")

SET(CMAKE_CXX_LINK_SHARED_LIBRARY)
SET(CMAKE_CXX_LINK_MODULE_LIBRARY)
#SET(CMAKE_C_LINK_SHARED_LIBRARY)
SET(CMAKE_C_LINK_MODULE_LIBRARY)


# build IOP_BIN
SET(CMAKE_C_LINK_EXECUTABLE
    "<CMAKE_C_COMPILER> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> -o <TARGET> <LINK_LIBRARIES>"
    "md5sum <TARGET>"
)

# build IOP_LIB
SET(CMAKE_C_CREATE_STATIC_LIBRARY
    "<CMAKE_AR> cru <TARGET> <LINK_FLAGS> <OBJECTS>"
    "iop-size <TARGET>"
)

SET(PS2 1)
SET(IOP 1)
