#
# CMake toolchain file for PS2 IOP processor
#
# Copyright (C) 2009-2010 Mathias Lafeldt <misfire@debugon.org>
#

INCLUDE(CMakeForceCompiler)

SET(CMAKE_SYSTEM_NAME Generic)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR iop)

CMAKE_FORCE_C_COMPILER(iop-gcc GNU)
CMAKE_FORCE_CXX_COMPILER(iop-g++ GNU)

SET(PS2DEV "$ENV{PS2DEV}")
IF (NOT PS2DEV)
    MESSAGE(FATAL_ERROR "PS2DEV env var not set.")
ENDIF (NOT PS2DEV)

SET(CMAKE_FIND_ROOT_PATH "${PS2DEV}/iop")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(PS2SDK "$ENV{PS2SDK}")
IF (NOT PS2SDK)
    MESSAGE(FATAL_ERROR "PS2SDK env var not set.")
ENDIF (NOT PS2SDK)

INCLUDE_DIRECTORIES("${PS2SDK}/iop/include")
INCLUDE_DIRECTORIES("${PS2SDK}/common/include")

SET(PS2 1)
SET(IOP 1)
